//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_RobotArmControl p_RobotArmControl;
        
        public static SteamVR_Input_ActionSet_RobotArmControl RobotArmControl
        {
            get
            {
                return SteamVR_Actions.p_RobotArmControl.GetCopy<SteamVR_Input_ActionSet_RobotArmControl>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_RobotArmControl = ((SteamVR_Input_ActionSet_RobotArmControl)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_RobotArmControl>("/actions/RobotArmControl")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.RobotArmControl};
        }
    }
}
