//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_RobotArmControl : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.robotArmControl_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.robotArmControl_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.robotArmControl_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.robotArmControl_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPadUp
        {
            get
            {
                return SteamVR_Actions.robotArmControl_TouchPadUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPadRight
        {
            get
            {
                return SteamVR_Actions.robotArmControl_TouchPadRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPadDown
        {
            get
            {
                return SteamVR_Actions.robotArmControl_TouchPadDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPadLeft
        {
            get
            {
                return SteamVR_Actions.robotArmControl_TouchPadLeft;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.robotArmControl_Pose;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.robotArmControl_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadSetOnHead
        {
            get
            {
                return SteamVR_Actions.robotArmControl_HeadSetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.robotArmControl_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.robotArmControl_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.robotArmControl_Haptic;
            }
        }
    }
}
